# Generated by Django 4.2.5 on 2023-09-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rental_total_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('rented', 'Rented'), ('sold', 'Sold')], default='Available', max_length=50, null=True),
        ),
    ]
